name: BuildTest
on: [pull_request]
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          
      - name: Install Dependencies
        run: dotnet workload restore ./OpusSharp.Core/OpusSharp.Core.csproj

      - name: Build
        run: dotnet build ./OpusSharp.Core/OpusSharp.Core.csproj -f netstandard2.0 -p:TargetFrameworks=netstandard2.0
