name: Deploy Site
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # SDK Version to use.

    - name: Deploy
      working-directory: ./Docs
      run: |
        dotnet workload restore
        dotnet run -- deploy -l Debug
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
